name: continuous integration 🎲

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Copy .env.test
        run: php -r "file_exists('.env') || copy('.env.test', '.env');"
      - name: Clear Composer cache
        run: composer clear-cache
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Quality
        run: make cs-ci
      - name: Unit and Feature tests
        run: make test
